######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 30 14:16:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
